title: Brandon Ritchie Yang
logo: image/profile_image.jpg
description: Data Science Undergraduate with a strong foundation in data analysis, machine learning, and deep learning. Eager to apply skills in an internship to solve real-world problems and contribute to data-driven solutions. Passionate about learning and growing in the field of data science.
show_downloads: true
theme: jekyll-theme-minimal
