title: Brandon Ritchie Yang
logo: /image/Untitled design (1).png
description: Enthusiastic Data Science undergraduate with a keen interest in machine learning and deep learning. Seeking to apply knowledge in the data-driven industry.
show_downloads: true
theme: jekyll-theme-minimal
